### PR TITLE
Remove confusing output for status code output

### PR DESCRIPTION
**Pull request by rgevaert**

### CODE REVIEW

**Comment by phrawzty** [comment]
Not sure why this is confusing—this is literally a check to see if the response is `200` or not, therefore the output message is accurate.
https://github.com/phrawzty/check_http_json/blob/8e137819d5818f7c8da8337f2f096ef5814dc8fe/check_http_json.rb#L215-L216

**Comment by rgevaert** [comment]
Except when you pass other status codes to be also OK. Sorry I forgot to add to the commit msg.
By the way :wave: devopsdays co-orger here :)

**Comment by phrawzty** [comment]
> Except when you pass other status codes to be also OK. Sorry I forgot to add to the commit msg.

OK, but your PR doesn't address that. Again, the block of code you're referring to does one thing: checks a status code against 200, and if it's _not_ 200, outputs a message. The message—the only line of code modified in your PR—remains accurate. If you intend for functionality to change, you'll need to do more than change the message.

> By the way 👋 devopsdays co-orger here :)

Hi Rudy. :)

**Comment by xorpaul** [comment]
@rgevaert Check out if #49 does what you want.

It does for me :)

**Pull request closed without merging**
